# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Extensible CLI to easily manage the authorization of your data sources."
  homepage "https://raito.io"
  version "0.66.3"
  license "Apache v2"

  on_macos do
    on_intel do
      url "https://github.com/raito-io/cli/releases/download/v0.66.3/raito-0.66.3-darwin_amd64.tar.gz"
      sha256 "255925b42c71f9ba8ece074deb87aebf25b95ebea8c850426cdf2d63319970ed"

      def install
        bin.install "raito"
        bash_completion.install "completions/raito.bash" => "raito"
        zsh_completion.install "completions/raito.zsh" => "_raito"
        fish_completion.install "completions/raito.fish"
      end
    end
    on_arm do
      url "https://github.com/raito-io/cli/releases/download/v0.66.3/raito-0.66.3-darwin_arm64.tar.gz"
      sha256 "a05704ebac4ab7e29a1922c966bbf2649b5f52107cd9b5ebfce130e473357630"

      def install
        bin.install "raito"
        bash_completion.install "completions/raito.bash" => "raito"
        zsh_completion.install "completions/raito.zsh" => "_raito"
        fish_completion.install "completions/raito.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raito-io/cli/releases/download/v0.66.3/raito-0.66.3-linux_amd64.tar.gz"
        sha256 "f907813a8ce25fea58a92530c1babc0ae1b11a558b849e9a67b55ef50e8467ed"

        def install
          bin.install "raito"
          bash_completion.install "completions/raito.bash" => "raito"
          zsh_completion.install "completions/raito.zsh" => "_raito"
          fish_completion.install "completions/raito.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raito-io/cli/releases/download/v0.66.3/raito-0.66.3-linux_arm64.tar.gz"
        sha256 "690a881d713f2fa2d220161af7e965f392dd2ddc5dee00e74c8e8a38437f682a"

        def install
          bin.install "raito"
          bash_completion.install "completions/raito.bash" => "raito"
          zsh_completion.install "completions/raito.zsh" => "_raito"
          fish_completion.install "completions/raito.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/raito -v"
  end
end
