# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Raito < Formula
  desc "Extensible CLI to easily manage the authorization of your data sources."
  homepage "https://raito.io"
  version "0.1.0"
  license "Apache v2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raito-io/cli/releases/download/v0.1.0/raito_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "b23126a9443e28d07ca35d15f45d0bb4d59bacbcf2c213e6c2b7d0680219dddc"

      def install
        bin.install "raito"
        bash_completion.install "completions/raito.bash" => "raito"
        zsh_completion.install "completions/raito.zsh" => "_raito"
        fish_completion.install "completions/raito.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raito-io/cli/releases/download/v0.1.0/raito_0.1.0_Darwin_arm64.tar.gz"
      sha256 "c14eb44de21117cd37852bd22efb90cda30824d182159bb6eeee6c96e9a45825"

      def install
        bin.install "raito"
        bash_completion.install "completions/raito.bash" => "raito"
        zsh_completion.install "completions/raito.zsh" => "_raito"
        fish_completion.install "completions/raito.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raito-io/cli/releases/download/v0.1.0/raito_0.1.0_Linux_arm64.tar.gz"
      sha256 "be5e12a3e81c3a192a3b233f12d533a1562af306975076e6861f414a1d663c8b"

      def install
        bin.install "raito"
        bash_completion.install "completions/raito.bash" => "raito"
        zsh_completion.install "completions/raito.zsh" => "_raito"
        fish_completion.install "completions/raito.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/raito-io/cli/releases/download/v0.1.0/raito_0.1.0_Linux_x86_64.tar.gz"
      sha256 "29d365f65a4af13eb9300ffd4b045d3d8ac7a2038a37305ffede76360eb626ef"

      def install
        bin.install "raito"
        bash_completion.install "completions/raito.bash" => "raito"
        zsh_completion.install "completions/raito.zsh" => "_raito"
        fish_completion.install "completions/raito.fish"
      end
    end
  end

  test do
    system "#{bin}/raito -v"
  end
end
